### ISSUE TITLE
Can't reassign request to another specialist

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#424] opened 2022-03-10 17:48 UTC
SUMMARY
I tried editing a request assigned to me to send it to another specialist, but it continues to be assigned to me despite a success message 

STEPS TO REPRODUCE
- sign in to staging
- add a request assigned to yourself
- Click edit on that request
- Change the assigned specialist
- click save (note the success banner)
- refresh the page (just to be sure. Needing to refresh may be a separate issue)

RESULTS
Expected - the request is no longer in "My Requests"
Actual - it is still in "My Requests"

REGRESSION TESTING
This does NOT seem to be a regression. As of filing this bug (3/10/22) I can reproduce this on the demo environment too. 

VIDEO
https://www.loom.com/share/7cc9f8ef5ca1420f9ce3669aac28bf87

**Comment by phorne-uncharted** [comment] 2022-05-03 16:52
I just tried this on staging. The result I got matched the expected result (i.e. the request was reassigned). I do not know if some other previous fix happened to fix this as well, or if this is a transient issue.

**Comment by karlolsonuc** [comment] 2022-05-03 16:57
Duplicate of #499, which has been fixed

**Closed by karlolsonuc** 2022-05-03 16:57 UTC
Labels: bug
