### ISSUE TITLE
Reporting page says No Results Found when it should say Loading…

### ISSUE THREAD

**Issue by danielfe** [microsoft/community-organization-operations-suite#562] opened 2022-05-05 17:31 UTC
On the reporting page when data is loading, the message on the page says "No Results Found". In fact, it is still loading and soon enough the results pop in. 

See video
https://www.loom.com/share/1afb6ac3e2664984a42939e0f8f46062

**Comment by phorne-uncharted** [comment] 2022-05-13 12:56
Duplicate of #505

**Closed by phorne-uncharted** 2022-05-13 12:56 UTC

**Comment by phorne-uncharted** [comment] 2022-05-17 14:44
The fix works well for requests and services, but the client table still has the wrong message when loading.

**Comment by GutherieDEV** [comment] 2022-05-19 15:22
There are three reporting options: Clients, Requests and Services.  Requests and services use graphql to acquire data during the user interaction.  The state is being correctly reported now and the appropriate message appears while the query is underway.

Clients, on the other hand, acquire data from a local state management API (Recoil, see useContactList.ts). The current version uses  useRecoilState to gather the contact information (no load state information).  I have tested replacing useRecoilState with useRecoilStateLoadable to track the state of the load and return it back for use generation of the correct message during load but it doesn't seem to ever enter a 'loading' state.  The 'no data' message is very brief and seems to exist during the first render of the page so the impact is minimal but it is an incorrect message.

Issue of cached data needs to be discussed (compliance to privacy rules) and perhaps alter the method used to load client data.

**Comment by GutherieDEV** [comment] 2022-05-24 18:21
Resolved (in meeting): remove recoil and use GraphQL (as is used for the other two reports.
