### ISSUE TITLE
Empty Service List

### ISSUE THREAD

**Issue by phorne-uncharted** [microsoft/community-organization-operations-suite#640] opened 2022-06-21 19:52 UTC
When coming from the dashboard (or directly after login), the service list remains empty despite getting data back from the server. If the user navigates to another page (other than dashboard), then returns to the service list, services appear. If the user does a search, then the service listing also displays the right information.

**Steps:**
Login to the application
From the dashboard, click services

**Expected Outcome:**
After waiting for the load to complete, the table should list the services

**Actual Outcome:**
After waiting for the load to complete, the table is empty

**Comment by mdeitner** [comment] 2022-07-04 22:49
Duplicate of #651

**Closed by mdeitner** 2022-07-04 22:49 UTC
Labels: Engineering
