### ISSUE TITLE
New requests disappear on browser refresh (on integ server)

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#366] opened 2022-03-01 15:18 UTC
Newly created requests disappear when browser is refreshed

NOTE observed on integ server only. Could not reproduce on demo

**Comment by ThomasKapler** [comment] 2022-03-01 20:26
See below update from demo testing: There may be a regression in the dev branch causing the issue in integ. This should be high priority fix before push to production.

[3:22 p.m.] dfeld (Guest)
    
One thing that may be helpful in debugging… if i add a request and assign to myself it doesnt show up until i refresh. BUT if i edit a requst assigned to someone else and assign it to me it does, an tehn after that if i add a request it shows up without refreshing. 

unable to reproduce the "request going away on refresh" issue.

​

**Comment by danielfe** [comment] 2022-03-16 15:18
Unable to reproduce on Safari this morning

**Comment by ThomasKapler** [comment] 2022-03-16 17:21
I am still seeing his on Integ. Suggest that first step in the issue is to do an engineering investigation into why Requests are not being saved on integ, and ARE saved on staging/demo

**Comment by karlolsonuc** [comment] 2022-03-28 18:35
Double checked and found this also reproduces in Chrome & Firefox on the Mac on integ. Looking at the network traffic, everything is coming back as a success, with no obvious difference in the posted json to and the response from graph ql between integ, demo and local testing . I thought it might be something to do with console log errors about wss:// connections being interrupted on load, but the same thing happens on the demo, and it doesn't have those issues.

**Comment by karlolsonuc** [comment] 2022-03-30 22:51
Added some richer logging around the possible trouble spot here. I'll check the integration logs to see if that tells us enough to act on or not.

**Comment by karlolsonuc** [comment] 2022-03-31 18:35
Clearing the bad data has fixed integration, so I'm closing this issue. We've also added a separate issue to make the logic & returns more tolerant & robust in should this event occur again in future: 
- https://github.com/microsoft/community-organization-operations-suite/issues/485

**Closed by karlolsonuc** 2022-03-31 18:35 UTC
Labels: bug
