### ISSUE TITLE
New "Notes" field appears without a label in the "show fields" list chooser.

### ISSUE THREAD

**Issue by ThomasKapler** [microsoft/community-organization-operations-suite#494] opened 2022-04-06 15:42 UTC
See below - the blank checkbox at the bottom of the fields chooser is for the "Notes" field on clients. The "Notes" label also does not appear in the table above the column.

![image](https://user-images.githubusercontent.com/98921014/162014060-4e71e375-f178-4618-b257-25bcfdc11746.png)

**Comment by phorne-uncharted** [comment] 2022-04-06 17:52
duplicate of #437

**Closed by phorne-uncharted** 2022-04-06 17:52 UTC
